### Create A DataFrame from dictionary

In [1]:
import pandas as pd

In [2]:
data = [{'name': 'vikash', 'age': 27}, {'name': 'Satyam', 'age': 14}]

In [4]:
df = pd.DataFrame.from_dict(data, orient='columns')

In [5]:
df

     name  age
0  vikash   27
1  Satyam   14

In [6]:
#If the Dictionary is nested you first need to normalize iter

data = [
  {
    'name': {
      'first': 'vikash',
      'last': 'singh'
    },
    'age': 27
  },
  {
    'name': {
      'first': 'satyam',
      'last': 'singh'
    },
    'age': 14
  }
]

In [10]:
from pandas import json_normalize
df = pd.DataFrame.from_dict(json_normalize(data), orient='columns')

In [11]:
df

   age name.first name.last
0   27     vikash     singh
1   14     satyam     singh